# Export Configuration for /sdp:export-issues command
# Determines where task breakdowns should be exported

# Export destination: "github" or "local"
# - github: Create issues directly in GitHub (requires gh CLI)
# - local:  Generate markdown files and import scripts locally
destination: github

# GitHub export settings
github:
  # Target repository in "owner/repo" format
  # If not specified, gh CLI will auto-detect from current git repository
  repo: your-org/your-repo

  # Issue export mode
  # - "sub_issues": Create tasks as sub-issues (requires gh sub-issue extension (gh extension install yahsan2/gh-sub-issue))
  # - "linked_issues": Create tasks as regular issues and link them to parent
  # - "single_issue": Create one issue with all tasks as checkboxes
  issue_mode: single_issue

  # Default labels to apply to all issues
  # These labels will be added to both main requirement issues and task sub-issues
  labels:
  #  - sdp
  #  - enhancement

  # Labels specific to main requirement issues
  # If not specified, only "requirement" will be added automatically
  # Uncomment and customize as needed:
  # main_issue_labels:
  #   - epic
  #   - planning

  # Labels specific to task sub-issues
  # If not specified, only "task" will be added automatically
  # Uncomment and customize as needed:
  # task_labels:
  #   - implementation
  #   - subtask

# Local export settings
local:
  # Output directory for generated files (relative to repository root)
  # Default: .sdp/out if not specified
  out_dir: .sdp/out