# Export Configuration for /sdp:export-issues command
# Determines where task breakdowns should be exported

# Export destination: "github", "jira", "backlog", or "local"
# - github:  Create issues directly in GitHub (requires gh CLI)
# - jira:    Create issues directly in Jira (uses REST API v3)
# - backlog: Create issues directly in Backlog (uses REST API v2)
# - local:   Generate markdown files locally
destination: github

# GitHub export settings
github:
  # Target repository in "owner/repo" format
  # If not specified, gh CLI will auto-detect from current git repository
  repo: your-org/your-repo

  # Issue export mode
  # - "sub_issues": Create tasks as sub-issues (requires gh sub-issue extension (gh extension install yahsan2/gh-sub-issue))
  # - "linked_issues": Create tasks as regular issues and link them to parent
  # - "single_issue": Create one issue with all tasks as checkboxes
  issue_mode: single_issue

  # Default labels to apply to all issues
  # These labels will be added to both main requirement issues and task sub-issues
  labels:
  #  - sdp
  #  - enhancement

  # Labels specific to main requirement issues
  # If not specified, only "requirement" will be added automatically
  # Uncomment and customize as needed:
  # main_issue_labels:
  #   - epic
  #   - planning

  # Labels specific to task sub-issues
  # If not specified, only "task" will be added automatically
  # Uncomment and customize as needed:
  # task_labels:
  #   - implementation
  #   - subtask

# Jira export settings
jira:
  # Jira instance URL (e.g., "https://your-domain.atlassian.net")
  url: https://your-domain.atlassian.net

  # Jira project key / space key (e.g., "PROJ", "DEV", "SCRUM")
  # In Jira UI this may be called "Space Key", but API uses it as project key
  project: YOUR-PROJECT

  # Authentication: Use API token (recommended) or set as environment variable
  # Create API token at: https://id.atlassian.com/manage-profile/security/api-tokens
  # Option 1: Set token directly (not recommended for security)
  # api_token: your-api-token-here
  # Option 2: Use environment variable (recommended)
  # Set environment variable: export JIRA_API_TOKEN=your-api-token-here
  # The command will read from environment variable if api_token is not set

  # Jira user email (required for authentication)
  email: your-email@example.com

  # Issue export mode
  # - "sub_tasks": Create tasks as sub-tasks (Jira native sub-tasks)
  # - "linked_issues": Create tasks as regular issues and link them to parent
  # - "single_issue": Create one issue with all tasks as checkboxes
  issue_mode: sub_tasks

  # Jira issue type for main requirement (e.g., "Epic", "Story", "Task")
  main_issue_type: Story

  # Jira issue type for task issues (e.g., "Sub-task", "Task")
  # Only used when issue_mode is "sub_tasks" or "linked_issues"
  task_issue_type: Sub-task

  # Jira component (optional)
  # component: Backend

  # Default labels to apply to all issues
  labels:
  #  - sdp
  #  - planning

# Backlog export settings
backlog:
  # Backlog space key (subdomain)
  # e.g., if your URL is https://myspace.backlog.com, space_key is "myspace"
  space_key: myspace

  # Backlog domain (default: backlog.com for international instances)
  # Use "backlog.jp" for Japanese instances
  domain: backlog.com

  # Backlog project key (shown in project settings)
  project_key: PROJ

  # Authentication: Use API key (recommended) or set as environment variable
  # Create API key at: 個人設定 > API > 登録
  # https://support-ja.backlog.com/hc/ja/articles/115015420567-API%E3%81%AE%E8%A8%AD%E5%AE%9A
  # Option 1: Set API key directly (not recommended for security)
  # api_key: your-api-key-here
  # Option 2: Use environment variable (recommended)
  # Set environment variable: export BACKLOG_API_KEY=your-api-key-here
  # The command will read from environment variable if api_key is not set

  # Issue export mode
  # - "sub_tasks": Create tasks as sub-tasks (Backlog native parent-child)
  # - "linked_issues": Create tasks as regular issues and link via comments
  # - "single_issue": Create one issue with all tasks as checkboxes
  issue_mode: single_issue

  # Backlog issue type for main requirement (e.g., "タスク", "バグ", "要望")
  main_issue_type: タスク

  # Backlog issue type for task issues (e.g., "タスク", "バグ")
  # Only used when issue_mode is "sub_tasks" or "linked_issues"
  task_issue_type: タスク

# Local export settings
local:
  # Output directory for generated files (relative to repository root)
  # Default: .sdp/out if not specified
  out_dir: .sdp/out