# Export Configuration for /sdp:export-issues command
# Determines where task breakdowns should be exported

# Export destination: "github" or "local"
# - github: Create issues directly in GitHub (requires gh CLI)
# - local:  Generate markdown files and import scripts locally
destination: github

# GitHub export settings
github:
  # Target repository in "owner/repo" format
  # If not specified, gh CLI will auto-detect from current git repository
  repo: your-org/your-repo

  # Default labels to apply to all issues
  # These labels will be added to both main requirement issues and task sub-issues
  labels:
  #  - sdp
  #  - enhancement

  # Labels specific to main requirement issues
  # If not specified, only "requirement" will be added automatically
  # Uncomment and customize as needed:
  # main_issue_labels:
  #   - epic
  #   - planning

  # Labels specific to task sub-issues
  # If not specified, only "task" will be added automatically
  # Uncomment and customize as needed:
  # task_labels:
  #   - implementation
  #   - subtask

# Local export settings
local:
  # Output directory for generated files (relative to repository root)
  # Default: out if not specified
  out_dir: out

  # Generate import script for batch creation
  # If true, creates a bash script to automate issue creation via gh CLI
  generate_import_script: true

  # Include individual task body files
  # If true, creates separate .md files for each task body
  # Useful for manual review or selective import
  individual_files: false